import click
import os
import numpy as np
import pandas as pd
import pointblank as pb

from deepchecks.tabular import Dataset
from deepchecks.tabular.checks import FeatureLabelCorrelation

from sklearn import set_config
from sklearn.model_selection import train_test_split
from src.split_and_save import split_and_save

@click.command()
@click.option('--raw-data', default="data/raw", help="Directory containing raw data")
@click.option('--data-to', default="data/processed", help="Directory to place processed data in")
@click.option('--seed', type=int, default=123)

def main(raw_data, data_to, seed):
    """
    Performs validation checks, splits data into training and testing sets,
    and saves the files

    Parameters
    ----------
    raw_data : str
        Path to the CSV file `winequality-white.csv`,
    data_to : str
        Directory where the processed train and test datasets and the split datasets are saved.
    seed : int
        Random seed for reproducibility.

    Raises
    ------
    ValueError
        If the predictive power correlation check fails.

    Outputs
    -------
    train_df.csv : CSV file
        Contains 75% of the data for model training.
    test_df.csv : CSV file
        Contains 25% of the data for model testing.
    Feature/target-split CSV files are generated by `split_and_save()`.
    """
    np.random.seed(seed)
    set_config(transform_output="pandas")

    expected_cols = ['fixed_acidity',
                     'volatile_acidity',
                     'citric_acid',
                     'residual_sugar',
                     'chlorides',
                     'free_sulfur_dioxide',
                     'total_sulfur_dioxide',
                     'density',
                     'pH',
                     'sulphates',
                     'alcohol',
                     'quality']
  
    origin_df = pd.read_csv(os.path.join(raw_data, "winequality-white.csv"), sep=',', encoding='utf-8').drop(columns=['color'])

    schema = pb.Schema(columns=[('fixed_acidity', 'float64'),
                                ('volatile_acidity', 'float64'),
                                ('citric_acid', 'float64'),
                                ('residual_sugar', 'float64'),
                                ('chlorides', 'float64'),
                                ('free_sulfur_dioxide', 'float64'),
                                ('total_sulfur_dioxide', 'float64'),
                                ('density', 'float64'),
                                ('pH', 'float64'),
                                ('sulphates', 'float64'),
                                ('alcohol', 'float64'),
                                ('quality', 'int64')])

    # Validate that all columns exist, do not contain null values,
    # datatypes match the schema, and all rows in the table are distinct
    (pb.Validate(origin_df)
     .col_exists(columns=expected_cols)
     .col_vals_not_null(columns=expected_cols, thresholds=0.0)
     .col_schema_match(schema=schema)
     .rows_distinct()
     .interrogate())

    wine_quality_ds = Dataset(origin_df, label="quality", cat_features=[])

    # Checks that features in the dataset are not excessively correlated with the target variable
    check_feat_lab_corr = FeatureLabelCorrelation().add_condition_feature_pps_less_than(0.9)
    check_feat_lab_corr_result = check_feat_lab_corr.run(dataset=wine_quality_ds)

    if not check_feat_lab_corr_result.passed_conditions():
        raise ValueError("Feature-Label correlation exceeds the maximum acceptable threshold.")

    # Ensures all values in the target column fall within the expected range
    pb.Validate(origin_df).col_vals_between(columns="quality", left=0, right=10).interrogate()

    # Split the dataset into training and testing sets
    train_df, test_df = train_test_split(
        origin_df,
        test_size=0.25,
        random_state=seed,
        stratify=origin_df["quality"]
    )

    train_df.to_csv(os.path.join(data_to, "train_df.csv"), index=False)
    test_df.to_csv(os.path.join(data_to, "test_df.csv"), index=False)

    # Separate the features and target
    split_and_save(train_df, test_df, "quality", data_to)

if __name__ == '__main__':
    main()
